### ISSUE TITLE
Change branch for CKEditor repository and test.

### ISSUE THREAD

**Issue by atrus1701** [clas-web/uncc-mediawiki-utils#1]
Change repository branch to CKeditor_v4.

**Comment by atrus1701** [comment]
The latest version of MediaWiki converting to WYSIWYG-CKEditor editor (and calling it VisualEditor for some reason), so we may not need to use this editor.  I have changed the update script to use the CKEditor 4.5 branch and it seems to work fine.

**Comment by marpa** [comment]
no longer developing for this web application
